---
galaxy_info:
  author: WPN Operations team
  description: An Ansible role to install and configure Opendistro kibana
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - xenial
    - name: Debian
      versions:
        - stretch
  galaxy_tags:
    - docker

dependencies:
  - role: nephelaiio.plugins
  - role: nephelaiio.docker
    when: false
  - role: mhutter.docker-systemd-service
    when: false
